# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.

CFLAGS = -std=c++17 -O2
LDFLAGS = -lglfw -lvulkan -ldl -lpthread -lX11 -lXxf86vm -lXrandr -lXi

SRC_DIR := src
INC_DIR := include

SRC := $(wildcard $(SRC_DIR)/main.cpp)
INC := $(wildcard $(INC_DIR)/*.h)


default_target: all
.PHONY : default_target

all: $(SRC) $(INC)
		g++ $(CFLAGS) -I $(INC_DIR) -o main $(SRC)  $(LDFLAGS) 